parameters:
  ### MODEL ARCHITECTURE ###
  MODEL:
    value:
      RGB_ENCODER:
        ENCODER: "facebook/dinov3-vits16-pretrain-lvd1689m"
        IMAGE_SIZE: 224
        RETURN_SELECTED_LAYERS: [3, 6, 9,12]
      POL_ENCODER:
        EMBED_DIM: 384
        DEPTH: 4
        N_HEADS: 12
        PATCH_SIZE: 16
      CROSS_ATTN:
        EMBED_DIM: 384
        N_HEADS: 12
        DROPOUT: 0.1
        BI_DIRECTIONAL: False
      DECODER:
        FEATURE_DIM: 384  
        REASSEMBLE_OUT_CHANNELS: [48, 96, 192, 384] 
        REASSEMBLE_FACTORS: [4.0, 2.0, 1.0, 0.5] 
        READOUT_TYPE: "ignore"  
        USE_BN: False
        OUTPUT_IMAGE_SIZE: [224,224]
        OUTPUT_CHANNELS: 4
  ### DATA ###
  DATASETS:
    value:
      SCRREAM:
        ROOT_DIR: "/datasets/SCRREAM/"
        TRAIN_SCENES: []
        POLARIZATION_FORMAT: "single_file_clock"
        VAL_SCENES: ["scene09_full_00", "scene09_reduced_00"]
        RHO_S: 0.6
        EPS: 1.0e-8
        TARGET_SIZE: [224,224]
        RESIZE_MODE: "resize"
        USE_CACHE: True
        SIMPLIFY_UPSAMPLING: True
        FEW_IMAGES: False
      HOUSECAT6D:
        ROOT_DIR: "/datasets/HouseCat6D/"
        TRAIN_SCENES: []
        POLARIZATION_FORMAT: "single_file_clock"
        VAL_SCENES: "val"
        RHO_S: 0.6
        EPS: 1.0e-8
        TARGET_SIZE: [224,224]
        RESIZE_MODE: "resize"
        USE_CACHE: True
        SIMPLIFY_UPSAMPLING: True
        FEW_IMAGES: False
      POLARGB:
        ROOT_DIR: "/datasets/PolaRGB/"
        TRAIN_SCENES: "train"
        POLARIZATION_FORMAT: "separate_files"
        VAL_SCENES: "test"
        RHO_S: 0.6
        EPS: 1.0e-8
        TARGET_SIZE: [224,224]
        RESIZE_MODE: "resize"
        USE_CACHE: True
        SIMPLIFY_UPSAMPLING: True
        FEW_IMAGES: False

  BATCH_SIZE:
    value: 24
  WORKERS:
    value: 4
  SHUFFLE:
    value: True
  PIN_MEMORY:
    value: true
  PREFETCH_FACTOR:
    value: 2
  
  ### OPTIMIZATION ###
  LEARNING_RATE:
    values: [1.0e-3, 1.0e-4, 1.0e-5]
  WEIGHT_DECAY:
    value: 1.0e-6
  EPOCHS:
    value: 30
  GRADIENT_ACCUMULATION_STEPS:
    value: 4
  WARMUP_STEPS:
    value: 0
  
  LR_SCHEDULER: 
    value: 
      ONPLATEAU:
        PATIENCE: 10
        FACTOR: 0.1
      # COSINE:
      #   N_PERIODS: 1
      STEPWISE:
        N_STEPS: 2
        GAMMA: 0.5
      # EXPONENTIAL:
      #   GAMMA: 0.5

  SWITCH_OPTIMIZER_EPOCH:
    value: null
  OPTIMIZER_BOOTSTRAP_NAME:
    value: "Adam"
  OPTIMIZER_REFINING_NAME:
    value: "Adam"

  STEPWISESCHEDULER_NSTEPS:
    value: 4
  STEPWISESCHEDULER_GAMMA:
    value: 0.5
  
  EARLY_STOPPING_PATIENCE:
    value: 20
  SAVE_INTERVAL:
    value: 1000
  
  ### LOGGING AND WANDB ###
  LOG_INTERVAL:
    value: 1
  WANDB_LOG_INTERVAL:
    value: 4
  IMAGE_LOG_INTERVAL:
    value: 20
  NO_WANDB:
    value: False
  MODEL_WATCHER_FREQ_WANDB:
    value: 100
  WANDB_ENTITY:
    value: "unreflect-anything"
  WANDB_PROJECT:
    value: "UnReflectAnything"
  NOTES:
    value: ""

### WANDB SWEEP CONFIG ###
method: grid
metric:
  goal: minimize
  name: Validation/epoch/Loss

program: sweep_agent.py

project: UnReflectAnything  


