site_name: UnReflectAnything Documentation
repo_url: https://github.com/mertkiray/unreflect-anything
theme:
  name: material
  palette:
    scheme: slate
    primary: black


nav:
  - Home: index.md
  - Config Files: config.md
  - Dataset:
    - Dataset Folder Structure: dataset.md
    - The Dataset class: rgbp.md
    - Adding a new dataset: adding_a_new_dataset.md
  - Running Experiments: training.md
    
plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences