site_name: UnReflectAnything Documentation

theme:
  name: material
  palette:
    scheme: slate


nav:
  - Home: index.md
 
  - Dataset:
    - Dataset Folder Structure: dataset.md
    - The RGBP Dataset class: dataset/rgbp.md

    - Training: training.md
    
plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences